# Generated by Django 4.2 on 2023-04-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.CharField(db_index=True, max_length=300, primary_key=True, serialize=False, unique=True)),
                ('staff_name', models.CharField(max_length=300)),
                ('staff_dept', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StaffLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=300)),
            ],
        ),
    ]
