# Generated by Django 4.2 on 2023-04-09 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_login',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Staff', to='staff.stafflogin'),
        ),
        migrations.AddField(
            model_name='stafflogin',
            name='desc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stafflogin',
            name='login_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(db_index=True, max_length=300, primary_key=True, serialize=False),
        ),
    ]
