# Generated by Django 4.2 on 2023-04-11 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='staff_login',
        ),
    ]
