# Generated by Django 4.2 on 2023-04-11 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_remove_staff_staff_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stafflogin',
            name='desc',
        ),
        migrations.DeleteModel(
            name='OtherDets',
        ),
    ]
