# Generated by Django 4.2 on 2023-04-12 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastotherexams',
            name='roll_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastOtherExams', to='student.student'),
        ),
    ]
