# Generated by Django 4.2 on 2023-04-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastotherexams',
            name='year_of_exam',
            field=models.IntegerField(),
        ),
    ]
