# Generated by Django 4.2 on 2023-04-19 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_pastotherexams_roll_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PastOtherExams',
        ),
    ]
