# Generated by Django 4.2 on 2023-04-19 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_delete_pastotherexams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='present_percentage',
        ),
    ]
