# Generated by Django 4.2 on 2023-04-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_pastotherexams_year_of_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastotherexams',
            name='roll_no',
            field=models.CharField(max_length=100),
        ),
    ]
