# Generated by Django 4.2 on 2023-04-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_attendance_present_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='present_percentage',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
    ]
